= Developer documentation

:moduliths: ../../../target/spring-modulith-docs

== Overview
plantuml::{moduliths}/components.puml[format=svg,title="Overall component overview"]


== Customer
plantuml::{moduliths}/module-customer.puml[format=svg,title="Inventory component overview"]
include::{moduliths}/module-customer.adoc[]

== Catalog
plantuml::{moduliths}/module-catalog.puml[format=svg,title="Catalog component overview"]
include::{moduliths}/module-catalog.adoc[]

== Inventory
plantuml::{moduliths}/module-inventory.puml[format=svg,title="Inventory component overview"]
include::{moduliths}/module-inventory.adoc[]

== Orders
plantuml::{moduliths}/module-order.puml[format=svg,title="Order component overview"]
include::{moduliths}/module-order.adoc[]

== Notification
plantuml::{moduliths}/module-notification.puml[format=svg,title="Notification component overview"]
include::{moduliths}/module-notification.adoc[]

== PayPal
plantuml::{moduliths}/module-paypal.puml[format=svg,title="PayPal component overview"]
include::{moduliths}/module-paypal.adoc[]

== Shipping
plantuml::{moduliths}/module-shipping.puml[format=svg,title="Shipping component overview"]
include::{moduliths}/module-shipping.adoc[]


