logging.level:
  victor: DEBUG


spring.cloud.openfeign.client.config:
  shipping-provider:
    url: http://localhost:9999/shipping
  payment-gateway:
    url: http://localhost:9999/payment


# p6spy JDBC logging
decorator:
  datasource:
    p6spy:
      multiline: false
      log-format: "%(executionTime) ms|%(category)|connection %(connectionId)|%(sqlSingleLine)"
shipping:
  shipping-from-address: Our Address 99, 12345, Our City
