spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource: # standalone H2 DB
    url: jdbc:h2:tcp://localhost:9092/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa