logging.level:
  victor: DEBUG


spring.cloud.openfeign.client.config:
  shipping-provider:
    url: http://localhost:9999/shipping
  payment-gateway:
    url: http://localhost:9999/payment


payment:
  client-id: modulith-app

# p6spy JDBC logging
decorator:
  datasource:
    p6spy:
      multiline: false
      log-format: "%(executionTime) ms|%(category)|connection %(connectionId)|%(sqlSingleLine)"
